var calcul = [
["A12", "ml", "", "Pset_BaseQuantities : Length"],
["A131.1", "ml", "", "Pset_BaseQuantities : Length"],
["A131.2", "ml", "", "Pset_BaseQuantities : Length"],
["A131.3", "ml", "Question à poser à l'opérateur : le type de structure envisagé nécessite-t-il une protection complémentaire ?", "Pset_BaseQuantities : Length"],
["A132.1;m2", "De base, on met toutes les élévations en A132,2 , puis on interroge l'utilisateur pour lui demander si certaines sont en maçonnerie hourdée (-> A132,1)", "Pset_BaseQuantities : NetSideArea"],
["A132.2", "m2", "", "Pset_BaseQuantities : NetSideArea"],
["A132.3", "m2", "Si le mur à un coefficient de transmission thermique surfacique (U) alors c'est un mur isolé", "Pset_BaseQuantities : NetSideArea"],
["A133.1", "m2", "Question à l'opérateur : Repérer planchers sur TP, sur VS, sur VU", "Pset_BaseQuantities : NetArea"],
["A133.2", "m2", "", "Pset_BaseQuantities : NetArea"],
["A133.21", "m2", "", "Pset_BaseQuantities : NetArea"],
["A133.3", "m2", "Pour tous les planchers sur TP", "Pset_BaseQuantities : NetArea"],
["A133.4", "m2", "Parmi les planchers ci-avant", "Pset_BaseQuantities : NetArea"],
["A133.5", "m2", "Parmi les planchers ci-avant", "Pset_BaseQuantities : NetArea"],
["A211.1", "ml", "", "Pset_BaseQuantities : Length"],
["A211.2", "m2", "", "Pset_BaseQuantities : NetSideArea"],
["A211.3", "m2", "", "Pset_BaseQuantities : NetSideArea"],
["A211.4", "m2", "", "Pset_BaseQuantities : NetSideArea"],
["A212.1", "m2", "De base, tous les planchers sont sur appuis en A212.1, puis on demande à l'utilisateur de localiser les planchers en porte-à-faux (A212.2) ainsi que les saillies de façades : les coursives (A236.3) et les auvents/casquettes (A236.4). ", "Pset_BaseQuantities : NetSideArea"],
["A212.2", "m2", "", "Pset_BaseQuantities : NetSideArea"],
["A212.3", "m2", "", "Pset_BaseQuantities : GrossArea"],
["A212.4", "m2", "", "Pset_BaseQuantities : GrossArea"],
["A213.1", "m", "Lié à la destination du projet renseignée dans les caractéristiques générales indiquées en début de projet", "Pset_BaseQuantities : Length"],
["A213.2", "m", "Lié à la destination du projet renseignée dans les caractéristiques générales indiquées en début de projet", "Pset_BaseQuantities : Length"],
["A213.3", "m", "Lié à la destination du projet renseignée dans les caractéristiques générales indiquées en début de projet", "Pset_BaseQuantities : Length"],
["A213.33", "u", "", "Nombre d'occurrences"],
["A213.4", "m2", "", "Pset_BaseQuantities : GrossArea"],
["A221.1", "m2", "", "Pset_BaseQuantities : GrossArea"],
["A221.2", "m2", "", "Pset_BaseQuantities : GrossArea"],
["A221.3", "m2", "", "Pset_BaseQuantities : GrossArea"],
["A221.4", "m2", "De base, toute la surface du toit en couverture (A222.1), puis on interroge l'utilisateur sur les surfaces de verrière en toitures (A221.4), d'éclairement en toiture (A222.3), le nombre de dispositifs de ventilation et de désenfumage en toiture (A222.4) et les saillies de toitures (A222.6)", "Pset_BaseQuantities : GrossArea"],
["A222.1", "m2", "De base, toute la surface du toit en couverture (A222.1), puis on interroge l'utilisateur sur les surfaces de verrière en toitures (A221.4), d'éclairement en toiture (A222.3), le nombre de dispositifs de ventilation et de désenfumage en toiture (A222.4) et les saillies de toitures (A222.6)", "Pset_BaseQuantities : GrossArea"],
["A222.2", "m2", "", "Pset_BaseQuantities : GrossArea"],
["A222.3", "m2", "De base, toute la surface du toit en couverture (A222.1), puis on interroge l'utilisateur sur les surfaces de verrière en toitures (A221.4), d'éclairement en toiture (A222.3), le nombre de dispositifs de ventilation et de désenfumage en toiture (A222.4) et les saillies de toitures (A222.6)", "Pset_BaseQuantities : GrossArea"],
["A222.4", "U", "De base, toute la surface du toit en couverture (A222.1), puis on interroge l'utilisateur sur les surfaces de verrière en toitures (A221.4), d'éclairement en toiture (A222.3), le nombre de dispositifs de ventilation et de désenfumage en toiture (A222.4) et les saillies de toitures (A222.6)", "La quantité --> paramètre absent ds le Pset_RoofBaseQuantities"],
["A222.5", "m2", "", "Pset_BaseQuantities : GrossArea"],
["A222.6", "m", "De base, toute la surface du toit en couverture (A222.1), puis on interroge l'utilisateur sur les surfaces de verrière en toitures (A221.4), d'éclairement en toiture (A222.3), le nombre de dispositifs de ventilation et de désenfumage en toiture (A222.4) et les saillies de toitures (A222.6)", "Pset_BaseQuantities : GrossArea"],
["A222.7", "m", "On demande à l'opérateur d'inscrire la longueur des protections en toiture", "Pset_BaseQuantities : Length"],
["A231.1 ", "m2", "De base, tous les remplissages d'ossatures sont en parois opaques extérieures non porteuses (A231.1) puis on demande à l'opérateur de localiser les parois éclairantes (A231.2) et le bardage proprements dits (A232.1)", "Pset_BaseQuantities : GrossArea"],
["A231.3", "m2", "De base, tous les remplissages d'ossatures sont en parois opaques extérieures non porteuses (A231.1) puis on demande à l'opérateur de localiser les parois éclairantes (A231.2) et le bardage proprements dits (A232.1)", "Pset_BaseQuantities : GrossSideArea"],
["A232.1", "m2", "De base, tous les remplissages d'ossatures sont en parois opaques extérieures non porteuses (A231.1) puis on demande à l'opérateur de localiser les parois éclairantes (A231.2) et le bardage proprements dits (A232.1)", "Pset_BaseQuantities : GrossArea"],
["A232.2", "m2", "Lié aux bardages proprements dits (A232.2) : à prendre en compte uniquement si le champ précédent est rempli. ", "Pset_BaseQuantities : GrossArea"],
["A233.1", "m2", "", "Pset_BaseQuantities : Area"],
["A234.1 ", "m2", "De base, toutes les menuiseries extérieures ont une protection mécanique. On demande ensuite à l'utilisateur d'indiquer celle qui n'en ont pas et les gardes-corps (hors escaliers et mezzanines) (A234.2)", "Pset_BaseQuantities : Area"],
["A234.2 ", "m2", "L'opérateur doit saisir manuellement la surface des gardes-corps de menuiseries extérieures", "Pset_BaseQuantities : Area"],
["A235.1 ", "m2", "De base, tous les murs extérieurs ont comme traitement un revêtements appliqués (A235.1). On interroge ensuite l'opérateur afin qu'il localise les revêtements scellés ou collés (A235.2), les revêtements rapportés (hors isolation) (A235.3) et l'isolation par l'extérieur (A235.4)", "Pset_BaseQuantities : GrossArea"],
["A235.2", "m2", "De base, tous les murs extérieurs ont comme traitement un revêtements appliqués (A235.1). On interroge ensuite l'opérateur afin qu'il localise les revêtements scellés ou collés (A235.2), les revêtements rapportés (hors isolation) (A235.3) et l'isolation par l'extérieur (A235.4)", "Pset_BaseQuantities : GrossArea"],
["A235.3", "m2", "De base, tous les murs extérieurs ont comme traitement un revêtements appliqués (A235.1). On interroge ensuite l'opérateur afin qu'il localise les revêtements scellés ou collés (A235.2), les revêtements rapportés (hors isolation) (A235.3) et l'isolation par l'extérieur (A235.4)", "Pset_BaseQuantities : GrossArea"],
["A235.4", "m2", "De base, tous les murs extérieurs ont comme traitement un revêtements appliqués (A235.1). On interroge ensuite l'opérateur afin qu'il localise les revêtements scellés ou collés (A235.2), les revêtements rapportés (hors isolation) (A235.3) et l'isolation par l'extérieur (A235.4)", "Pset_BaseQuantities : GrossArea"],
["A236", "m2", "De base, toute la surface du toit en couverture (A222.1), puis on interroge l'utilisateur sur les surfaces de verrière en toitures (A221.4), d'éclairement en toiture (A222.3), le nombre de dispositifs de ventilation et de désenfumage en toiture (A222.4) et les saillies de toitures (A222.6)", "Pset_BaseQuantities : GrossArea"],
["A236.1", "m2", "On interroge directement l'opérateur afin qu'il localise les modénatures (A236.1) et les les balcons/loggias (A236.2) parmis les objets de cette famille", "Pset_BaseQuantities : GrossArea"],
["A236.2", "m2", "", "Pset_BaseQuantities : GrossArea"],
["A236.3", "m2", "De base, tous les planchers sont sur appuis en A212.1, puis on demande à l'utilisateur de localiser les planchers en porte-à-faux (A212.2) ainsi que les saillies de façades : les coursives (A236.3) et les auvents/casquettes (A236.4). ", "Pset_BaseQuantities : GrossArea"],
["A236.4", "m2", "", "Pset_BaseQuantities : GrossArea"],
["A241.2", "ml", "De base, tous les escaliers ont des travaux de finition. L'opérateur à la possibililté de localiser ceux qui n'en ont pas. ", "Pset_BaseQuantities : Length"],
["A242.1", "m2", "", "Pset_BaseQuantities : GrossArea"],
["A242.2", "m2", "De base, tous les rampes ont des travaux de finition. L'opérateur à la possibililté de localiser ceux qui n'en ont pas. ", "Pset_BaseQuantities : GrossArea"],
["A311.1", "m2", "", "Pset_BaseQuantities : NetSideArea"],
["A311.2", "m2", "", "Pset_BaseQuantities : NetSideArea"],
["A311.3", "m2", "", "Pset_BaseQuantities : NetSideArea"],
["A312.1", "m2", "Je ne sais pas l'exprimer … l'idée est de reproduire le lien d'appartenance d'un objet dans une zone", "Pset_BaseQuantities : Area"],
["A312.2", "m2", "Si un bloc-porte est renseigné d'au moins une de ces informations, alors on l'attribue à cette catégorie", "Pset_BaseQuantities : Area"],
["A312.4", "m2", "", "Pset_BaseQuantities : Area"],
["A312.5", "U", "", "Nombre d'occurrence"],
["A313.1", "m2", "De base on met tout en A313,2, et on demande à l'opérateur de repérer les élévations pour lesquelles on reste en maçonnerie apparente, et qui basculeront donc en A313,1", "Pset_BaseQuantities : NetSideArea (x2 si IsExternal = oui)"],
["A313.2", "m2", "", "Pset_BaseQuantities : NetSideArea (x2 si IsExternal = oui)"],
["A314.1", "m2", "", "Pset_BaseQuantities : NetSideArea"],
["A314.2", "m2", "", "Pset_BaseQuantities : NetSideArea"],
["A315.1", "m2", "Pour les IFCCeiling, ils sont à mapper par l'utilisateur, il n'y a pas de données intégrées qui permettent de les attribuer", "Pset_BaseQuantities : NetSideArea / Pset_BaseQuantities : NetArea"],
["A315.2", "m2", "", "Pset_BaseQuantities : NetArea"],
["A323.3", "m3", "", "Pset_BaseQuantities : GrossVolume"],
["A323.4", "m3", "", "Pset_BaseQuantities : GrossVolume"],
["A331.1", "m2", "De base on met tout en A331,1, et on demande à l'opérateur de repérer les élévations pour lesquelles on bascule en A331,2,  A331,3 ou A332", "Prendre le périmètre de la pièce (déduction faîte des séparateurs de pièce), à multiplier par la hauteur de la pièce, et déduire la surface des portes et fenêtres de la pièce"],
["A331.2", "m2", "De base on met tout en A331,1, et on demande à l'opérateur de repérer les élévations pour lesquelles on bascule en A331,2,  A331,3 ou A332", "Prendre le périmètre de la pièce (déduction faîte des séparateurs de pièce), à multiplier par la hauteur de la pièce, et déduire la surface des portes et fenêtres de la pièce"],
["A331.3", "m2", "", "Prendre le périmètre de la pièce (déduction faîte des séparateurs de pièce), à multiplier par la hauteur de la pièce, et déduire la surface des portes et fenêtres de la pièce"]
];
